In [99]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [100]:
# Load data
file_path = 'C:/Users/hp/Downloads/EMMADUNAMIX MAINTENACE 2025 - FIRST QUARTER EMMA DUNAMIX MARCH 2026 - Copy.csv'
df = pd.read_csv(file_path)
df

,,DATE,MECHANIC,TRUCK NUMBER,TRUCK DRIVER,ITEM PURCHASED,RATE,QTY,AMOUNT,LIST OF SPARE PARTS
0,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,BODY VALVE,"25,000",1,"25,000",NaN
1,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,22 PRESSURE HOSE,"7,000",1,"7,000",NaN
2,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,PISTON,"8,000",1,"8,000",NaN
3,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,HOSE KITTING,"2,000",2,"4,000",NaN
4,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,ADAPTER,"2,000",4,"8,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3735,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,IFEANYI EXPENSES,"162,000",1,"162,000",NaN
3736,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,PIA EXPENSES,"309,000",1,"309,000",NaN
3737,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,I.K EXPENSES,"80,000",1,"80,000",NaN
3738,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,TOBI'S EXPENSES,"82,000",1,"82,000",NaN
3739,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,KAMALI EXPENSES,"24,000",1,"24,000",NaN

In [101]:
# Cleaning logic
# 1. Rename columns (stripping whitespace)
df.columns = [col.strip() if col.strip() != "" else "MONTH_LABEL" for col in df.columns]
df.columns

Index(['MONTH_LABEL', 'DATE', 'MECHANIC', 'TRUCK NUMBER', 'TRUCK DRIVER',
       'ITEM PURCHASED', 'RATE', 'QTY', 'AMOUNT', 'LIST OF SPARE PARTS'],
      dtype='object')

In [102]:
#Clean numeric columns
def clean_numeric(val):
    if pd.isna(val) or str(val).strip() == '':
        return 0.0
    if isinstance(val, str):
        # Remove commas, any non-numeric except dot
        clean_val = "".join(c for c in val if c.isdigit() or c == '.')
        return float(clean_val) if clean_val else 0.0
    return float(val)

df['AMOUNT'] = df['AMOUNT'].apply(clean_numeric)
df['RATE'] = df['RATE'].apply(clean_numeric)
df['QTY'] = pd.to_numeric(df['QTY'], errors='coerce').fillna(0)
df

,MONTH_LABEL,DATE,MECHANIC,TRUCK NUMBER,TRUCK DRIVER,ITEM PURCHASED,RATE,QTY,AMOUNT,LIST OF SPARE PARTS
0,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,BODY VALVE,25000.0,1,25000.0,NaN
1,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,22 PRESSURE HOSE,7000.0,1,7000.0,NaN
2,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,PISTON,8000.0,1,8000.0,NaN
3,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,HOSE KITTING,2000.0,2,4000.0,NaN
4,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,ADAPTER,2000.0,4,8000.0,NaN
...,...,...,...,...,...,...,...,...,...,...
3735,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,IFEANYI EXPENSES,162000.0,1,162000.0,NaN
3736,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,PIA EXPENSES,309000.0,1,309000.0,NaN
3737,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,I.K EXPENSES,80000.0,1,80000.0,NaN
3738,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,TOBI'S EXPENSES,82000.0,1,82000.0,NaN
3739,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,KAMALI EXPENSES,24000.0,1,24000.0,NaN

In [103]:
df=df.drop('LIST OF SPARE PARTS', axis=1)
df

,MONTH_LABEL,DATE,MECHANIC,TRUCK NUMBER,TRUCK DRIVER,ITEM PURCHASED,RATE,QTY,AMOUNT
0,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,BODY VALVE,25000.0,1,25000.0
1,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,22 PRESSURE HOSE,7000.0,1,7000.0
2,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,PISTON,8000.0,1,8000.0
3,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,HOSE KITTING,2000.0,2,4000.0
4,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,ADAPTER,2000.0,4,8000.0
...,...,...,...,...,...,...,...,...,...
3735,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,IFEANYI EXPENSES,162000.0,1,162000.0
3736,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,PIA EXPENSES,309000.0,1,309000.0
3737,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,I.K EXPENSES,80000.0,1,80000.0
3738,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,TOBI'S EXPENSES,82000.0,1,82000.0
3739,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,KAMALI EXPENSES,24000.0,1,24000.0

In [104]:
# 3. Clean DATE
# Assuming format DD/MM/YYYY based on the snippet "02/03/2026"
# Note: "MARCH 02/03/2026" was shown in head, which means there's a prefix
def extract_date(val):
    if pd.isna(val): return None
    val = str(val).strip()
    # If the date starts with "MARCH", "FEBRUARY" etc followed by space
    parts = val.split()
    date_str = parts[-1] if parts else val
    return date_str

df['DATE_CLEAN'] = df['DATE'].apply(extract_date)
df['DATE_CLEAN'] = pd.to_datetime(df['DATE_CLEAN'], format='%d/%m/%Y', errors='coerce')
df

,MONTH_LABEL,DATE,MECHANIC,TRUCK NUMBER,TRUCK DRIVER,ITEM PURCHASED,RATE,QTY,AMOUNT,DATE_CLEAN
0,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,BODY VALVE,25000.0,1,25000.0,2026-03-02
1,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,22 PRESSURE HOSE,7000.0,1,7000.0,2026-03-02
2,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,PISTON,8000.0,1,8000.0,2026-03-02
3,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,HOSE KITTING,2000.0,2,4000.0,2026-03-02
4,MARCH,02/03/2026,KINGSLEY AIRMAN,KJA145YF,SUNDAY AIHAJI,ADAPTER,2000.0,4,8000.0,2026-03-02
...,...,...,...,...,...,...,...,...,...,...
3735,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,IFEANYI EXPENSES,162000.0,1,162000.0,2026-03-28
3736,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,PIA EXPENSES,309000.0,1,309000.0,2026-03-28
3737,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,I.K EXPENSES,80000.0,1,80000.0,2026-03-28
3738,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,TOBI'S EXPENSES,82000.0,1,82000.0,2026-03-28
3739,MARCH,28/03/2026,THIRD PARTY WEEKLY EXPENSES,NaN,NaN,KAMALI EXPENSES,24000.0,1,24000.0,2026-03-28

                 Emma Dunamix Maintenance Analysis: March 2026 Executive Summary
This report breaks down the financial and operational maintenance data for March 2026. The insights below are designed to highlight where the budget is going and which assets are requiring the most attention.

In [105]:
df['AMOUNT'] = pd.to_numeric(
df['AMOUNT'].astype(str).str.replace(r'[₦,]', '', regex=True),
    errors='coerce'
)

In [106]:

total_spent = df['AMOUNT'].sum()

formatted_total = f"₦{total_spent:,.0f}"

print(f"Total expenditure for March is {formatted_total}")

Total expenditure for March is ₦84,078,210

 ***Monthly Financial Expenditure***
 
This represents the total amount spent on all spare parts, repairs, and labor for the entire fleet during March.

**Financial Summary**  
The total expenditure for the month of March is **N84,078,210.00**  
*(Eighty-Four Million, Seventy-Eight Thousand, Two Hundred and Ten Naira).*

 **Analysis Detail**  
This total includes all recorded transactions, ranging from minor consumables such as grease to major expenses like engine overhauls and roadside rescue operations.

In [107]:
summary = df.groupby('TRUCK NUMBER').agg(
    total_cost=('AMOUNT', 'sum'),
    frequency=('TRUCK NUMBER', 'count')
).sort_values(by='frequency', ascending=False).head(10)

summary['total_cost'] = summary['total_cost'].round(0).astype(int)
summary['total_cost_formatted'] = summary['total_cost'].apply(lambda x: f"{x:,}")

summary

              total_cost  frequency total_cost_formatted
TRUCK NUMBER
LND669YF         2041000         93            2,041,000
AKD769XZ         1745000         89            1,745,000
LSD961XU         1451000         86            1,451,000
EKY181XZ         2460800         85            2,460,800
EPE839XZ         2240500         84            2,240,500
EPE210YA         1808000         83            1,808,000
KJA291YE         1684500         80            1,684,500
ABC710ZY         1690000         77            1,690,000
T19679LA         1228000         72            1,228,000
T5379LA          1372500         59            1,372,500

## Truck Usage & Cost Summary Analysis

## Objective

This analysis identifies the **top 10 most frequently used trucks** and evaluates their **total expenditure** within the dataset.


## Methodology

The analysis was performed using the following steps:

1. **Grouping Data**

   * The dataset was grouped by **Truck Number** to consolidate all records related to each truck.

2. **Aggregation**

   * Two key metrics were calculated:

     * **Total Cost**: Sum of all expenses associated with each truck
     * **Frequency**: Number of times each truck appears in the dataset (indicating usage level)

3. **Sorting**

   * Results were sorted by **frequency (descending)** to highlight the most actively used trucks.

4. **Top Selection**

   * The **top 10 trucks** were selected for focused analysis.

5. **Data Formatting**

   * Total cost values were rounded and converted to **whole numbers** for clarity and readability.

In [110]:
#Group by item to get count and sum
top_10 = df.groupby('ITEM PURCHASED')['AMOUNT'].agg(['count', 'sum']).reset_index()

# Rename columns and sort
top_10.columns = ['Item Name', 'Times Purchased', 'Total Amount']
top_10 = top_10.sort_values(by='Total Amount', ascending=False).head(30)

# Format the amount with commas
top_10['Total Amount'] = top_10['Total Amount'].apply(lambda x: f"{x:,.0f}")

print(top_10.to_string(index=False))

                  Item Name  Times Purchased Total Amount
               I.K EXPENSES               11    3,252,500
             SET OF BEARING               54    2,780,000
                     RESCUE               66    2,711,000
              NIYI EXPENSES               17    2,536,500
     ACCIDENTAL CASE RESCUE                1    2,250,000
                   GEAR OIL               99    2,053,000
                 ENGINE OIL               69    1,764,000
                   AXLE NUT               54    1,705,000
                WELDER WORK               79    1,542,000
               PIA EXPENSES               11    1,518,500
                WORKMANSHIP               31    1,299,000
                      RINGS                7    1,260,000
          PASSING OF TRUCKS               26    1,232,000
                     SLEEVE                6    1,100,000
        DOZZY OIL 25 LITRES               15    1,065,000
           IFEANYI EXPENSES               17    1,016,000
            RADIATOR SUPPLY                2    1,000,000
            DRILLING OF HUB               27      994,000
     METAL AND MAIN BEARING                5      900,000
            COMPLETE SPIZER               19      860,000
        SUPPLIED OF BATTERY                1      800,000
                     PISTON                8      788,000
             SET OF LINNING               15      760,000
                WHEEL SHAFT                5      750,000
            RENTING OF JACK              118      748,000
                       FUEL               73      732,560
                  TRANSPORT              242      681,000
WORKING INJECTOR AND NOZZLE                7      665,000
                     GREASE               93      625,000
                      METAL               11      614,000

In [111]:
# Grouping
repeated_items = df.groupby(
    ['TRUCK DRIVER', 'TRUCK NUMBER', 'ITEM PURCHASED']
).agg(
    How_Many_Times=('ITEM PURCHASED', 'count'),
    Total_Amount=('AMOUNT', 'sum'),
    Dates=('DATE', lambda x: ', '.join(x.dropna().astype(str).unique()))
).reset_index()

# Filter + Sort (best practice)
multi_items = repeated_items[
    repeated_items['How_Many_Times'] > 1
].sort_values(
    by=['How_Many_Times', 'Total_Amount'],
    ascending=[False, False]
)

# Format
multi_items_formatted = multi_items.head(50).copy()

multi_items_formatted['Total_Amount'] = (
    multi_items_formatted['Total_Amount']
    .round()
    .astype(int)
    .apply(lambda x: f"₦{x:,}")
)

print("REPEATED PURCHASES (SAME ITEM, SAME DRIVER, SAME TRUCK):")
print("-" * 100)
print(multi_items_formatted.to_string(index=False))

REPEATED PURCHASES (SAME ITEM, SAME DRIVER, SAME TRUCK):
----------------------------------------------------------------------------------------------------
   TRUCK DRIVER TRUCK NUMBER      ITEM PURCHASED  How_Many_Times Total_Amount                                                                  Dates
       CHIGOZIE     T19679LA           TRANSPORT               6      ₦17,000             09/03/2026, 16/03/2026, 21/03/2026, 23/03/2026, 28/03/2026
     LEKAN WEST     LSD961XU           TRANSPORT               6      ₦17,000             03/03/2026, 13/03/2026, 19/03/2026, 25/03/2026, 26/03/2026
      CHIMA OGA     ABC710ZY           TRANSPORT               6      ₦15,000 03/03/2026, 05/03/2026, 09/03/2026, 11/03/2026, 20/03/2026, 25/03/2026
     TAYE OKELE     EPE210YA           TRANSPORT               6      ₦14,000             07/03/2026, 12/03/2026, 21/03/2026, 26/03/2026, 28/03/2026
      GBOLAHAUN     SMK219XZ              RESCUE               5     ₦181,000                         02/03/2026, 09/03/2026, 14/03/2026, 16/03/2026
      TAYE TOMI     LSD793XZ            GEAR OIL               5     ₦112,000             07/03/2026, 13/03/2026, 16/03/2026, 19/03/2026, 26/03/2026
      CHIMA OGA     ABC710ZY              GREASE               5      ₦51,000             03/03/2026, 05/03/2026, 11/03/2026, 20/03/2026, 28/03/2026
      OLA ADISA     KRD437YF           TRANSPORT               5      ₦21,000                         07/03/2026, 12/03/2026, 14/03/2026, 16/03/2026
      CHIMA OGA     ABC710ZY                FUEL               5      ₦20,000             03/03/2026, 05/03/2026, 11/03/2026, 20/03/2026, 25/03/2026
  BOLAJI RILWAN     LND669YF           TRANSPORT               5      ₦15,000             06/03/2026, 12/03/2026, 19/03/2026, 27/03/2026, 28/03/2026
   ABDUL RAHMAN     LND209YF           TRANSPORT               5      ₦14,000             03/03/2026, 12/03/2026, 14/03/2026, 17/03/2026, 21/03/2026
      TAYE TOMI     LSD793XZ           TRANSPORT               5      ₦13,000             04/03/2026, 13/03/2026, 16/03/2026, 19/03/2026, 26/03/2026
         FRIDAY     EKY181XZ           TRANSPORT               5      ₦12,000             05/03/2026, 07/03/2026, 12/03/2026, 25/03/2026, 28/03/2026
     BABA MORUF     BDG711XZ              RESCUE               4     ₦205,000                         02/03/2026, 05/03/2026, 23/03/2026, 26/03/2026
      CHIMA OGA     ABC710ZY            AXLE NUT               4     ₦130,000                         03/03/2026, 05/03/2026, 11/03/2026, 20/03/2026
       CHIGOZIE     T19679LA            GEAR OIL               4      ₦86,000                         07/03/2026, 21/03/2026, 23/03/2026, 28/03/2026
        RASHEED     KSF690XV            GEAR OIL               4      ₦84,000                         02/03/2026, 04/03/2026, 16/03/2026, 25/03/2026
          OKELE     PKA540YR            GEAR OIL               4      ₦70,000                         07/03/2026, 13/03/2026, 25/03/2026, 28/03/2026
       MUSTAPHA     AKD769XZ TRANSPORT TO IBADAN               4      ₦60,000                                                 04/03/2026, 06/03/2026
  ALFA SULEIMAN      PKA67YR           TRANSPORT               4      ₦28,000                         02/03/2026, 06/03/2026, 13/03/2026, 17/03/2026
        RASHEED     KSF690XV     RENTING OF JACK               4      ₦26,000                         04/03/2026, 07/03/2026, 25/03/2026, 28/03/2026
  BOLAJI RILWAN     LND669YF  TRANSPORT TO DOYIN               4      ₦12,000                                     20/03/2026, 21/03/2026, 27/03/2026
         FRIDAY     EKY181XZ TRANSPORT TO BERGER               4      ₦10,000                         05/03/2026, 14/03/2026, 16/03/2026, 27/03/2026
         OGHENE      T5379LA           TRANSPORT               4      ₦10,000                         09/03/2026, 17/03/2026, 23/03/2026, 28/03/2026
     ADAMS DARE     WDE698YE           TRANSPORT               4       ₦9,000                         02/03/2026, 03/03/2026, 11/03/2026, 28/03/2026
          CHIDI     EPE783YA           TRANSPORT               4       ₦9,000                                     07/03/2026, 09/03/2026, 17/03/2026
      CHIMA OGA     ABC710ZY      SET OF BEARING               3     ₦170,000                                     03/03/2026, 11/03/2026, 20/03/2026
      TAYE TOMI     LSD793XZ      SET OF BEARING               3     ₦170,000                                     13/03/2026, 16/03/2026, 26/03/2026
     BABA MORUF     BDG711XZ      SET OF BEARING               3     ₦135,000                                     02/03/2026, 04/03/2026, 23/03/2026
      TAYE TOMI     LSD793XZ            AXLE NUT               3      ₦95,000                                     13/03/2026, 16/03/2026, 26/03/2026
    SEGUN ILAJE     LND665YF              RESCUE               3      ₦92,000                                     02/03/2026, 23/03/2026, 28/03/2026
     BABA MORUF     BDG711XZ            AXLE NUT               3      ₦90,000                                     02/03/2026, 04/03/2026, 23/03/2026
          OKELE     PKA540YR              RESCUE               3      ₦90,000                                     09/03/2026, 20/03/2026, 25/03/2026
         AKANJI     WDE564YE              RESCUE               3      ₦84,000                                     06/03/2026, 20/03/2026, 24/03/2026
     TAYE OKELE     EPE210YA         BURNER WORK               3      ₦75,000                                     02/03/2026, 12/03/2026, 21/03/2026
      OGBON INU     LND666YF          ENGINE OIL               3      ₦72,000                                     05/03/2026, 14/03/2026, 21/03/2026
       FEMI NEW     WDE565YE            GEAR OIL               3      ₦64,000                                     13/03/2026, 17/03/2026, 26/03/2026
     LEKAN WEST     LSD961XU            GEAR OIL               3      ₦60,000                                     03/03/2026, 19/03/2026, 26/03/2026
         SIKIRU     GGE187XY         WELDER WORK               3      ₦55,000                                     24/03/2026, 25/03/2026, 27/03/2026
         SAMSON     LND211YF     WORKING OF TIRE               3      ₦40,000                                     06/03/2026, 09/03/2026, 28/03/2026
MOHAMMED YINUSA     FKJ498XZ     WORKING OF TIRE               3      ₦36,000                                     05/03/2026, 19/03/2026, 24/03/2026
         OGHENE      T5379LA              GREASE               3      ₦33,000                                     13/03/2026, 17/03/2026, 28/03/2026
   ABDUL RAHMAN     LND209YF                FUEL               3      ₦32,000                                     12/03/2026, 14/03/2026, 17/03/2026
      TAYE TOMI     LSD793XZ              GREASE               3      ₦29,000                                     13/03/2026, 16/03/2026, 26/03/2026
    FEMI OMOAME      T5378LA     RENTING OF JACK               3      ₦21,000                                     02/03/2026, 05/03/2026, 17/03/2026
         JOSEPH     AGL502YC     RENTING OF JACK               3      ₦21,000                                     11/03/2026, 13/03/2026, 18/03/2026
MOHAMMED YINUSA     FKJ498XZ     RENTING OF JACK               3      ₦19,000                                     05/03/2026, 19/03/2026, 24/03/2026
           NURU     AAA370XZ     RENTING OF JACK               3      ₦19,000                                     06/03/2026, 11/03/2026, 17/03/2026
    SEGUN COACH     LND210YF     RENTING OF JACK               3      ₦19,000                                     04/03/2026, 18/03/2026, 27/03/2026
     BABA MORUF     BDG711XZ              GREASE               3      ₦18,000                                     02/03/2026, 04/03/2026, 23/03/2026